export const types = Object.freeze({
    // Sync
    WEATHER_SELECT_DAY: 'WEATHER_SELECT_DAY',
    WEATHER_FILL_DAYS: 'WEATHER_FILL_DAYS',
    WEATHER_FILTER_DAYS: 'WEATHER_FILTER_DAYS',
    WEATHER_START_FETCHING: 'WEATHER_START_FETCHING',
    WEATHER_STOP_FETCHING: 'WEATHER_STOP_FETCHING',
    WEATHER_SET_FETCHING_ERROR: 'WEATHER_SET_FETCHING_ERROR',
    // Async
    WEATHER_FETCH_DAYS_ASYNC: 'WEATHER_FETCH_DAYS_ASYNC',
});
